### ISSUE TITLE
Support UPDATE

### ISSUE THREAD

**Issue by s3u** [ql-io/ql.io#10]

**Comment by s3u** [comment]
Thought you may be interested in taking a stab at this.

**Comment by s3u** [comment]
This needs to work for route dependencies too (see load-routes.js)

**Comment by prabhakhar** [comment]
Syntax
Type 1
    `
        update <table> 
    set n1 = v1 [, n2 = v2] 
`
    ni is a JSONPath expression [ with optional array subscript]
    vi is a value or ql.io expression. (optional {})

Yes, there is no where clause, as the update statement degenerates (typically) to a http ‘put’, having a where adds confusion.

Type 2 (Opaque Style)
        `
    update <table>
    using ( <XML>)
`

Examples
1. 

```
update items
set title = “Initial”, time = ’12:30’
```

2.

```
userid = <value [from a select]>
update items
set title = ‘Next’,
    seller = userid
```

3.

```
update items
set items[0].itemid = 1,
    items[1].itemid = 2,
    items[0].name = ‘one’,
    items[1].name = ‘two’
```

**Comment by prabhakhar** [comment]
The above is not very usable.

The syntax that is to be implemented is:

```
 update <table-name> with <JSON Object>
```

**Comment by prabhakhar** [comment]
Examples:

```
 var item = { "name" : "pilot", 
                   "color" : "red" }; 
 update items with item;
```

**Comment by prabhakhar** [comment]
https://github.com/ql-io/ql.io/pull/525 delivers this feature.
