### ISSUE TITLE
Oauth example

### ISSUE THREAD

**Issue by s3u** [ql-io/ql.io#121]

**Comment by shimonchayim** [comment]
OAuth examples created here: 
https://github.com/ql-io/ql.io-site/blob/master/tables/twitter.home.ql
https://github.com/ql-io/ql.io-site/blob/master/tables/twitter.signin.js

Documentation available here:
https://github.com/ql-io/ql.io-site/blob/master/public/views/docs/oauth.ejs

**Comment by s3u** [comment]
Integrating ...
