### ISSUE TITLE
Guidelines required for debugging monkey patches and body templates (Mustache files)

### ISSUE THREAD

**Issue by shimonchayim** [ql-io/ql.io#154]

**Comment by s3u** [comment]
Cylus - can you explain?

**Comment by shimonchayim** [comment]
Folks generally end-up making errors while creating their monkey patch files or Mustache files. They end-up debugging by having console.log statements which can be painful. Question is should we provide guidance on how to debug this through say Intellij, etc.

**Comment by s3u** [comment]
Got it. Mustache files don't worry me as you can look at HAR traces. But good point about patches.
