### ISSUE TITLE
Assertion Error : Value is undefined

### ISSUE THREAD

**Issue by arekatla** [ql-io/ql.io#168]
Engine throws '  Assertion Error : Value is undefined' for a select statement. Here is the error message

"name": "AssertionError",
"message": "value is undefined",
"actual": null,
"expected": true,
"operator": "==",
"stack": "AssertionError: value is undefined\n at [object Object].addParam
Steps to reproduce the issue
1) Create table using below url
create table ebay.finding.advanced on 
select get from 'http://svcs.ebay.com/services/search/FindingService/v1?OPERATION-NAME=findItemsAdvanced&SERVICE-VERSION={^version}&GLOBAL-ID={globalid}&SECURITY-APPNAME={apikey}&RESPONSE-DATA-FORMAT={format}&REST-PAYLOAD&keywords={keywords}&categoryId={categoryId}&paginationInput.entriesPerPage={limit}&paginationInput.pageNumber={pageNumber}&outputSelector%280%29=SellerInfo&sortOrder={sortorder}'

2) Run the below command in console
  Select \* from ebay.finding.advanced

**Comment by s3u** [comment]
@arekatla - I'm not able to reproduce this. I tried

http://ql.io/console?s=create%20table%20ebay.finding.advanced%20on%20%0Aselect%20get%20from%20'http%3A%2F%2Fsvcs.ebay.com%2Fservices%2Fsearch%2FFindingService%2Fv1%3FOPERATION-NAME%3DfindItemsAdvanced%26SERVICE-VERSION%3D%7B%5Eversion%7D%26GLOBAL-ID%3D%7Bglobalid%7D%26SECURITY-APPNAME%3D%7Bapikey%7D%26RESPONSE-DATA-FORMAT%3D%7Bformat%7D%26REST-PAYLOAD%26keywords%3D%7Bkeywords%7D%26categoryId%3D%7BcategoryId%7D%26paginationInput.entriesPerPage%3D%7Blimit%7D%26paginationInput.pageNumber%3D%7BpageNumber%7D%26outputSelector%25280%2529%3DSellerInfo%26sortOrder%3D%7Bsortorder%7D'%0A%0Aselect%20*%20from%20ebay.finding.advanced

on ql.io/console.

**Comment by arekatla** [comment]
@s3u - I am also not able to reproduce the same so marking as closed.
