### ISSUE TITLE
Object manipulation

### ISSUE THREAD

**Issue by s3u** [ql-io/ql.io#196]
The language currently supports object selection as in 

```
foo = "{bar.foo}";
```

But the lang supports no way to update value of bar.foo.

One option is to use insert, update and delete operations. Here is an example.

```
obj = {
  "p1" : "v1",
  "p2" : {
      "p3" : "v3",
      "p4" : "v4"
  }
};

p2 = "{obj.p2}";
insert into p2 (p5, p6) values ('v5', 'v6')
return obj;
```

But this is not ideal. The lang should be much simpler

```
foo = bar.foo;
```

   bar.foo = 'fool';
   return bar.foo;

This should return `fool`.

**Comment by s3u** [comment]
Pull req https://github.com/ql-io/ql.io/pull/197 has some of the changes.

**Comment by s3u** [comment]
Actually, it is much simpler and convenient to use UDFs on the LHS for this behavior - see https://github.com/ql-io/ql.io/issues/502

**Comment by shimonchayim** [comment]
UDFs support it. For now closing this.
