### ISSUE TITLE
count?

### ISSUE THREAD

**Issue by s3u** [ql-io/ql.io#20]
How do I know the number of results returned?

**Comment by jmrodriguez** [comment]
We could take advantage of this feature. For instance:

```
messagesResponse = select * from myMessagesAPI where userId = "{userId}";
messages = "{messagesResponse.$..Message}";

return {
  "messages" : "{messages}"
}
```

Right now, if we only wanted to know how many messages the specified user has, we would have to return a complete array with all the Message objects in it and do something like:

```
messageArray = response.messages;  
messagesCount = messagesArray.length; 
```

on the client side.

If we had a count function available we could do something like this instead:

```
messagesResponse = select * from myMessagesAPI where userId = "{userId}";
messages = "{messagesResponse.$..Message}";
messageCount = select count(*) from messages;
return {
  "messageCount" : "{messageCount}"
}
```

and make the API response shorther, hence faster :P

**Comment by shimonchayim** [comment]
this functionality is available through UDF.
