### ISSUE TITLE
Missing pre-requisite for Build an App

### ISSUE THREAD

**Issue by tcng** [ql-io/ql.io#201]
When I follow the instructions in http://ql.io/docs/build-an-app
I got quite a few unmet npm dependencies, including node-markdown, websocket-server, connect-assetmanager etc. and the server would not start one.

It seems one would have to first do a git clone of ql-io/ql.io and do a "make install" first. Then follow the steps described in Build An App.

**Comment by s3u** [comment]
I could not reproduce this. Do you happen to have the npm-debug.log file still?

**Comment by tcng** [comment]
I have the above problem with Mac.

When I started from a clean ubuntu install and the instructions work fine.

**Comment by x2on** [comment]
Same problem here on Mac OS X Lion. Building ql.io from source fixed the issue.

**Comment by s3u** [comment]
@x2on do still have the npm-debug.log captured when it failed?

**Comment by sggraham32** [comment]
Am having the same problem on Mac.  It seems to be related to XML2JSON dependency on expat.

This may be related to the header expat.h not being found.  Where is the install looking for the file?  I have an expat.h in my system, but for some reason it is not being found by the install.

Here is a snippet from the install out:

npm http 304 https://registry.npmjs.org/node-expat/1.4.1

> node-expat@1.4.1 install /Users/sgg/ql.io/modules/console/node_modules/xml2json/node_modules/node-expat
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
Checking for header expat.h              : not installed 
/Users/sgg/ql.io/modules/console/node_modules/xml2json/node_modules/node-expat/wscript:13: error: the configuration failed (see '/Users/sgg/ql.io/modules/console/node_modules/xml2json/node_modules/node-expat/build/config.log')
npm ERR! node-expat@1.4.1 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the node-expat@1.4.1 install script.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 11.4.0
npm ERR! command "node" "/usr/local/bin/npm" "link"
npm ERR! cwd /Users/sgg/ql.io/modules/console
npm ERR! node -v v0.8.6
npm ERR! npm -v 1.1.48
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/sgg/ql.io/modules/console/npm-debug.log
npm ERR! not ok code 0
make[1]: **\* [install] Error 1
npm link ql.io-compiler;\
    npm link ql.io-console;\
    npm link ql.io-engine;\
    npm install;\
    npm link; \

help?

**Comment by shimonchayim** [comment]
You will see above:

Checking for node path : not found 
Checking for node prefix : ok /usr/local 
Checking for header expat.h : not installed 

trying doing "which node" do you see if it is installed. And also you need to install expat.

e.g. on Ubuntu you would do:

sudo apt-get install expat libexpat1-dev

**Comment by isnolan** [comment]
yum install expat-devel
