### ISSUE TITLE
make clean install test failing

### ISSUE THREAD

**Issue by mtipnis** [ql-io/ql.io#242]
I ran make clean install test in my directory and got the following error.

I can also see this error intermittently on http://travis-ci.org/#!/ql-io/ql.io in builds 59,61,62

./node_modules/ql.io-ecv -> /usr/local/lib/node_modules/ql.io-ecv -> /Users/mtipnis/stack/ql.io-public/modules/ecv
./node_modules/ql.io-compiler -> /usr/local/lib/node_modules/ql.io-compiler -> /Users/mtipnis/stack/ql.io-public/modules/compiler
./node_modules/ql.io-console -> /usr/local/lib/node_modules/ql.io-console -> /Users/mtipnis/stack/ql.io-public/modules/console
./node_modules/ql.io-engine -> /usr/local/lib/node_modules/ql.io-engine -> /Users/mtipnis/stack/ql.io-public/modules/engine

/usr/local/bin/ql.io.app -> /usr/local/lib/node_modules/ql.io-app/bin/ql.io-app.js
/usr/local/lib/node_modules/ql.io-app -> /Users/mtipnis/stack/ql.io-public/modules/app
node_modules/.bin/nodeunit test

test-mon
✔ check test setup

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:640:11)
    at Object.afterConnect [as oncomplete](net.js:631:18)
make[1]: **\* [test] Error 1
make: [test] Error 2 (ignored)

The CI fails because of this as well.

**Comment by mtipnis** [comment]
I have commented out test-mon for now

**Comment by s3u** [comment]
@mtipnis can't reproduce this. There may be a timing issue on slower machines as this test does start script dance. Try increasing the time it waits.
