### ISSUE TITLE
Native JSON data type support for response

### ISSUE THREAD

**Issue by smunamala** [ql-io/ql.io#250]
The response returned from the  ql.io server is all of type string. It is not identifying  numeric or boolean values in the native json type.

**Comment by s3u** [comment]
This is related to xml2json.

**Comment by s3u** [comment]
The changes I'm working on will do things:
- any quoted number will be coerced to a number
- quoted 'true' and '1' will be coerced to true
- quoted 'false' and '0' will be coerced to false.

**Comment by s3u** [comment]
The first step is to update xml2json to optionally coerce numbers and booleans. See https://github.com/ql-io/node-xml2json.

**Comment by s3u** [comment]
Fixed with https://github.com/ql-io/ql.io/pull/258
