### ISSUE TITLE
Enable caching in the ql.io cluster

### ISSUE THREAD

**Issue by smunamala** [ql-io/ql.io#251]
We are looking for an ability to cache response for  certain requests so that the no.of hits to the service are reduced and at the same time save IO time.

**Comment by s3u** [comment]
Pending items from emails and previous comments:
1. compute key should not be called when the expires clause is not present. This function should only be able to override as its name suggests.
2. Both accept and accept-encoding need to be included as the origin may have used the values of those in serving a response.
3. cache key length issues?
4. Not sure if you noticed, but
   
   create table foo on insert post to 'foo' expires 10;

is allowed per your peg change. Such statements should not be possible as on select is idempotent and safe.

**Comment by shimonchayim** [comment]
Fixing 1.

Comments for 2, 3, 4 captured in the following discussion
https://github.com/ql-io/ql.io/pull/364

**Comment by shimonchayim** [comment]
This is fixed .. working with some users to make sure everything is working.
