### ISSUE TITLE
Ability to pass the values from preprocess (patch uri) to postprocess (patch response)

### ISSUE THREAD

**Issue by smunamala** [ql-io/ql.io#255]
Currently, there is no ql.io framework support to pass the values from preprocess (patch uri) to postprocess (patch response) int he monkey patch for a single request execution.

We need this support so that the user can avoid using global variables that is causing issues between request executions.

**Comment by s3u** [comment]
Can you give an example?

**Comment by smunamala** [comment]
For example, we are reusing the body template for a service operation for two different usecases.  

In one usecase, depending on the request parameters passed, I need to include the readset from the template  and  process the items returned in the response, 
In the second use case, I am not interested in the readset, but need to include a different block in the template and process the aspect histogram details returned in the response.

So, the post process needs to know what kind of usecase so that the response is processed accordingly.

**Comment by s3u** [comment]
Thanks. It makes sense. Will update soon.

**Comment by s3u** [comment]
The fix will pass resourceUri, statement, and params to `patch status`, `patch uri`, and `patch response` methods. You can add data to params object and retrieve it in `patch response`.

**Comment by s3u** [comment]
Fixed via https://github.com/ql-io/ql.io/pull/260.
