### ISSUE TITLE
Need support to return response in XML format

### ISSUE THREAD

**Issue by smunamala** [ql-io/ql.io#262]
We need an option from ql.io middle tier  to return the response back to client in XML format instead of json.

**Comment by s3u** [comment]
Here is what this will do:
1. When sending a request to a route, include either `format=xml` param or a header `Accept: application/xml`.
2. The engine will convert the response to XML using https://github.com/buglabs/node-xml2json.
3. This process will not guarantee that returned XML follows any set conventions.
4. The response will have no scheme associated.

**Comment by prabhakhar** [comment]
Agreed. 

Take the case of a script return a list if ItemIds. The json is [1,2,3,4]. This can't be expressed in xml. 
[{'id': '1'}, [{'id'} : '2'}] can be expressed 

``` xml
<data>
<id> 1 </id>
<id> 2 </id>
</data>.
```

Thinking.

**Comment by s3u** [comment]
I prefer not to do this. This does not make sense.

**Comment by s3u** [comment]
Closing. Death to XML.
