### ISSUE TITLE
Get routes with similar names but different query parameters does not resolve correctly

### ISSUE THREAD

**Issue by shimonchayim** [ql-io/ql.io#286]
For e.g:

We had following 3 routes with different query parameters

getaspects_catid_dp.ql -- /getaspects?searchbycategoryid={categoryid}&producttypename={producttype}
getaspects_key_dc.ql -- /getaspects?searchbykeyword={keyword}
getaspects_key_dp.ql -- /getaspects?searchbykeyword={keyword}&producttypename={producttype}
When we were calling route 3 with parameters searchbykeyword={keyword}&producttypename={producttype}, route 2 was getting called instead with one parameter searchbykeyword={keyword}

**Comment by shimonchayim** [comment]
A bug in app.js. Know the fix. Doing it now.

**Comment by shimonchayim** [comment]
Fix was incomplete...:-(

**Comment by prjande** [comment]
verified the fix. The Get routes are now resolved correctly.
