### ISSUE TITLE
Be able to disable /q in the console

### ISSUE THREAD

**Issue by s3u** [ql-io/ql.io#31]

**Comment by prabhakhar** [comment]
I understand we need to do this only for production instances.
Question is,  if we disable  /q, how to test some query without a route?
ecv check also uses /q.

**Comment by s3u** [comment]
> Question is, if we disable /q, how to test some query without a route?

The idea is to prevent this ability.

> ecv check also uses /q.

which needs to be redone - perhaps by using a canned route "/all".

**Comment by s3u** [comment]
ecv.js should poke /tables or /routes

**Comment by prabhakhar** [comment]
https://github.com/ql-io/ql.io/pull/261 delivers this feature.
