### ISSUE TITLE
Dynamic params from udf with OAuth integration?

### ISSUE THREAD

**Issue by x2on** [ql-io/ql.io#329]
How is it possible to use udf functions in statement which are considered in the OAuth Part.
On my example below the request uses the udf parameter, but the OAuth uri doesn't know the parameter from the udf.

Any ideas?

im using the following select statement

``` sql
select * from testtable where param('test')
```

the create table statement:

``` sql
create table testtable
    on select get from "http://rest.example.com/function/testValue={testValue}" 
    using patch "testPatch.js"
```

and patch:

``` javascript
exports['udf'] = function() {
  return {
        'testValue' : function(a) {
            if (a == 'test') {
                return 'TESTVALUE'
            }
            else {
                return 'OTHERVALUE'
            }
        }
    };
};

var uriTemplate = require('ql.io-uri-template');

var OAuth= require('oauth').OAuth;

exports['patch headers'] = function(options) {
    var h = options.headers;

    var uri = uriTemplate.parse(options.statement.uri).format(options.params);

    var oa = new OAuth("",
    "",
    "Key", "Secret",
    "1.0", "http://localhost:3000/oauth/callback", "HMAC-SHA1", null);

    var orderedParameters = oa._prepareParameters("",
        "", "GET",
        uri);

    var authorization = oa._buildAuthorizationHeaders(orderedParameters);

    h["Authorization"] = authorization;

    return h;
};
```

**Comment by s3u** [comment]
Not sure I understand the question, but allow me to clarify how UDFs work.

The purpose if udf is to allow a patch to manufacture params using some inputs from selects. Here is an example.

```
select * from foo where bar(2, 3)
```

Let's say, bar returns the min of 2 and 3. Then the params will hold

```
params = {
    "bar": 2
}
```

Please see https://github.com/ql-io/ql.io/blob/master/modules/engine/test/patch/udf.[js|ql] for an example. The params computed should be available for OAuth work.

**Comment by x2on** [comment]
I think that this is exactly what im doing or?

But in the OAuth patch headers

``` javascript
var uri = uriTemplate.parse(options.statement.uri).format(options.params);
```

doesn't contain this parameter...

**Comment by s3u** [comment]
Thanks. Checking ...

**Comment by s3u** [comment]
Here is the example I just tried.

```
exports['udf'] = function() {
    return {
        'p1' : function(arg) {
            return arg
        },
        'p2' : function(a, b) {
            return Number(a) + Number(b);
        }
    };
};

exports['patch uri'] = function(args) {
    console.log(args.params.p1);
    console.log(args.params.p2);
    return args.uri;
}
```

Given a statement

```
select * from patch.udf where p1("v1") and p2("2", "3")'
```

this prints

```
v1
5
```

on the console.

Can you try with the latest from npm?

**Comment by s3u** [comment]
I added a test to verify that this is working. 

https://github.com/ql-io/ql.io/pull/354

**Comment by x2on** [comment]
But this only works if "p1" or "p2" is not a query parameter defined in the create table statement. If you define it as a parameter like the testValue above then the params are undefined.

How could i define that "p1" should be used as the "testvalue" above?

**Comment by s3u** [comment]
I see it. Working on a fix. Sorry for hastily closing.

**Comment by s3u** [comment]
https://github.com/ql-io/ql.io/pull/385 has the fix.

**Comment by s3u** [comment]
Pushed to npm.

ql.io-engine-0.4.23 has the fix.
