### ISSUE TITLE
multi line comment syntax for .ql files

### ISSUE THREAD

**Issue by hochang** [ql-io/ql.io#340]
Currently we only have -- for single line comment for .ql files
for example
--this is a comment
As writing lots of .ql files daily, I feel we need to support multiple lines comment
some suggestions:

""" this is a python style comment 
It supports line break"""

/\* This is a java style comment
Isn't it awesome?*/

**Comment by s3u** [comment]
Fixed - https://github.com/ql-io/ql.io/pull/484
