### ISSUE TITLE
Route logic -  join condition based on arrays with in an object

### ISSUE THREAD

**Issue by smunamala** [ql-io/ql.io#384]
For example,  In the following  values of a1 and a2,  I need to return only the brand name ("Brand-A"  and "Brand-C")  and count for "Gravati", since it exists in both a1 and a2.

```
a1 = [{
    "name": "Brand-A",
    "ns": "df",
    "aspectValue" : [{ "name": "Gap"},
                     {"name": "Addidas"}, 
                     {"name": "Gravati"}] 
  },
  {
    "name": "Brand-B",
    "ns": "df",
    "aspectValue" : [{ "name": "Gap"},{"name": "Addidas"}] 
  }, 
  {
    "name": "Brand-C",
    "ns": "df",
    "aspectValue" : [{ "name": "Gravati"},{"name": "Addidas"}]
  }];

a2 = [{  
    "name": "Brand-A",
    "ns": "df",
    "aspectDetails": [{"name": "Gravati","count": 32},
                      {"name": "Florsheim by Duckie Brown","count": 18}]
  }, 
  {
    "name": "Brand-C",
    "ns": "df",
    "aspectDetails": [{"name": "Gravati","count": 32},
                      {"name": "Florsheim by Duckie Brown","count": 18}]
  }];
```

Desired Result:

Only  "Graviti" from  a2 - Brand-A and Brand-C   because it  has a corresponding entry in a1 - "Brand-A" and "Brand -C" .  
- "Florsheim by Duckie Brown"  from a2 - "Brand -A" and "Brand-B" should be eliminated, because it doesn't exist  in corresponding  a1 -  "Brand-A" and  "Brand-B".
  
  So, the final result should look like below
  
    [
        ["Brand-A", "df", {"name": "Gravati", "count": 32}],
        ["Brand-C", "df", {"name": "Gravati", "count": 32}]
    ]

**Comment by s3u** [comment]
I think I figured out how the syntax would look like

```
select a2.name, a2.ns, a2.aspectDetails[?(@.name === "Gravati")]  from a2 as a2, a1 as a1 
   where a1.name = a2.name
```

In this statement, `aspectDetails` is filtered based on an expression.

@smunamala - Does this capture your intent?

**Comment by smunamala** [comment]
can the value "Gravati"  be replaced with an expression similar to " (a1.aspectValue[@.name])"? If so, it should be fine. What does the "?" in the expression: (@.name === "Gravati") stands for ?

**Comment by s3u** [comment]
In order to support this, the language and the need to accommodate the following:
- JSONPath in column clauses
- JSONPath in LHS and RHS of '=' conditions in where clauses
- Script expressions in JSONPath 
- User defined functions

This is cool stuff.

**Comment by s3u** [comment]
See https://gist.github.com/2227815 for the final outcome.

**Comment by s3u** [comment]
See https://gist.github.com/2334012 for the updated UDF support to solve this use case. See https://github.com/ql-io/ql.io/pull/416/files#L13R32 for the implementation of the UDF.
