### ISSUE TITLE
Document ` to escape params

### ISSUE THREAD

**Issue by s3u** [ql-io/ql.io#395]
We need to document this on http://ql.io/docs/uri-template.

Thanks for the poke by @mulder - https://twitter.com/#!/nickmulder/status/184254997050036224

**Comment by mulder** [comment]
I'll gladly take care of this; 

Are the docs maintained in the ql.io-site repo?  Hand coded?

**Comment by s3u** [comment]
https://github.com/ql-io/ql.io-site is the app that runs on http://ql.io. Please look for uri-template.ejs.

**Comment by mtipnis** [comment]
https://github.com/ql-io/ql.io-site/pull/38
