### ISSUE TITLE
SSL support in ql.io

### ISSUE THREAD

**Issue by abhinavkumar** [ql-io/ql.io#456]
How would ql.io support SSL requests ? Is it planned on roadmap ?

**Comment by hochang** [comment]
Currently ql.io uses HTTP protocol. Haven't heard any future plan using SSL
Thank you and best regards
Hongcheng Chang

On 5/9/12 11:27 AM, "abhinavkumar"
<reply+i-4498497-4d76486a8018f2aa65035726160d238e1d6537cd-1302440@reply.git
hub.com> wrote:

**Comment by s3u** [comment]
This is fairly trivial to do.

Right now, we call

```
express.createServer()
```

in app.js. We need to pass the private key and a cert.

**Comment by s3u** [comment]
Already supported.
