### ISSUE TITLE
Error handling in ql.io scripts

### ISSUE THREAD

**Issue by abhinavkumar** [ql-io/ql.io#457]
I would like to request a doc covering ...
1) How does error handling happen in ql.io ? 
2) What all errors are taken care of or exposed to the user script ? Network errors ? Service errors ?
3) What configurations are exposed around handling errors ?

**Comment by s3u** [comment]
This is partly covered under https://github.com/ql-io/ql.io/wiki/%5BProposal%5D-Optional-Inputs-and-Errors. Conditional work is pending though

**Comment by shimonchayim** [comment]
Conditional params and fallback work complete
