### ISSUE TITLE
Possible testing scenarios for optional params

### ISSUE THREAD

**Issue by mtipnis** [ql-io/ql.io#464]
Here are few scenarios for testing of optional params feature:

1) Route with optional and required
Pass only optional
Test should fail

2) Route with optional and required
Pass only required
Test should pass

3) Route with optional and required
Pass neither
Test should fail

4) Route with optional and required
Both have default values
 (a) Pass neither, both defaults should get picked up : Test should pass
 (b) Pass both, No defaults should get picked up : Test should pass
 (c) Pass optional, default of required should get picked up, Test should pass

5) Route with multiple required params
Pass only one required
Tess should fail

6) Route with multiple required
Some have default values
  (a) Pass required that don't have default, Test should pass
  (b) Pass only those required that have default, Test should fail

**Comment by hochang** [comment]
following test cases are already added:

1) Route with optional and required
Pass only optional
Test should fail

2) Route with optional and required
Pass only required
Test should pass

3) Route with optional and required
Pass neither
Test should fail

4) Route with optional and required
Both have default values
(a) Pass neither, both defaults should get picked up : Test should pass
(b) Pass both, No defaults should get picked up : Test should pass
(c) Pass optional, default of required should get picked up, Test should pass

In addition, added defaults in regular route.
