### ISSUE TITLE
insert statement doesn't handle multiple item inserts

### ISSUE THREAD

**Issue by mtipnis** [ql-io/ql.io#492]
insert into abc (Order.Methods, Order.A.Transaction.Item.ItemID,
Order.A.Transaction.TransactionID, Order.A.Transaction.Item.ItemID,
Order.A.Transaction.TransactionID ) values ("However you want to pay", "1234", "0","6789","0")

Request XML :

```
<Request> 
<Order>
    <Methods>However you want to pay</Methods>
<A>
<Transaction>
<Item>
    <ItemID>110025788368</ItemID>
</Item>
    <TransactionID>0</TransactionID>
</Transaction>
</TransactionArray>
</A>
</Order>
</Request> 
```

**Comment by s3u** [comment]
This is related to https://github.com/ql-io/ql.io/issues/504.

**Comment by mtipnis** [comment]
Testcase : 
https://github.com/ql-io/ql.io/blob/master/modules/engine/test/insert-into-test.js
