### ISSUE TITLE
Finish up UDF on columns clause

### ISSUE THREAD

**Issue by s3u** [ql-io/ql.io#500]

**Comment by khurrumqureshi** [comment]
Does we have have udf support for column clause like
udfs = require('myudfs');
return select id, myudfs.sum(price, tax, shipping) from product where zip = 98074;

exports.sum = function(price, tax, shipping) {
    // first arg is error, second result
    return this.next(null, price + tax + shipping);
}

or does it will implement in future.

**Comment by jasxie** [comment]
Hongcheng, 

I think the 'column clause support of UDF' is in place. Please check. If yes, close the issue. If not, bring this to Cylus and me for a discussion
