### ISSUE TITLE
Document UDF on RHS of assignments

### ISSUE THREAD

**Issue by s3u** [ql-io/ql.io#503]

**Comment by jasxie** [comment]
hongcheng,

is it you to document? If not, re-assign to madura. thanks!

**Comment by hochang** [comment]
This seems already documented on the site.

**Comment by mbellmbell** [comment]
I don't see the documentation on http://ql.io/docs/udf.  And I think it would also be useful to describe how to write a udf that is called iteratively for each row vs. a udf that is on rhs (e.g., use of "this" and the return statement)
