### ISSUE TITLE
Limit clause

### ISSUE THREAD

**Issue by jmrodriguez** [ql-io/ql.io#51]
In some cases, we might be interested in getting only the first X results returned by a query. For instance, if we have an API that might return many items that match a given search criteria, we could use a limit clause to get the first 5 of them, like this:

```
items = select Item from itemAPI where {some condition} limit 5
```

Additionally, this could also be used to implement pagination for those APIs that support such feature.

```
items = select Item from itemAPI where {some condition} limit 5, 5
```

would return the items 5 to 10 from the original response

Something very similar to MySQL's LIMIT syntax (http://dev.mysql.com/doc/refman/5.0/es/select.html):

```
[LIMIT {[offset,] row_count | row_count OFFSET offset}]
```

**Comment by s3u** [comment]
This is already possible provided you can map limit to offset to some inputs in a table. What's not possible yet is applying those in process.

**Comment by s3u** [comment]
This is now done :)
