### ISSUE TITLE
"EventEmitter memory leak detected" message in the console

### ISSUE THREAD

**Issue by prabhakhar** [ql-io/ql.io#512]
I saw the following stack trace at the server side, if I increase the concurrent users at the client side. For higher no of users, I saw this stack trace is emitted at a very high rate. This happens for both gzip and non-gzip responses.

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
   at Socket.<anonymous> (events.js:139:15)
   at Socket.once (events.js:160:8)
   at Socket.setTimeout (net.js:143:12)
   at ClientRequest.setTimeout (http.js:1388:17)
   at ClientRequest.<anonymous> (http.js:1400:10)
   at ClientRequest.g (events.js:156:14)
   at ClientRequest.emit (events.js:88:20)
   at Array.0 (http.js:1346:9)
   at EventEmitter._tickCallback (node.js:190:38)

**Comment by s3u** [comment]
Could it be related to the fix in https://github.com/ql-io/ql.io/pull/511? Could you see if this happens after your fix as well?

**Comment by prabhakhar** [comment]
After the fix also, the issue is happening. I tested with ql.io-engine - 0.6.9 which has the fix for 511

**Comment by prabhakhar** [comment]
The trace is due to  - line 323 in req.js -  clientRequest.setTimeout(timeout, function() {}) that we have added.

standalone node program https://gist.github.com/2963290 can reproduce this issue.

**Comment by s3u** [comment]
Interesting finding! We could instrument a build of node to see if the listener list keeps growing in this test.

**Comment by prabhakhar** [comment]
Logged issue on node : https://github.com/joyent/node/issues/3505

**Comment by s3u** [comment]
@prabhakhar -- see my comments on https://github.com/joyent/node/issues/3505. 

IMO, it is better to increase `maxSockets` from the default of `5` with.

```
http.globalAgent.maxSockets = 1000;
```

to avoid request backlog on any given socket.

**Comment by prabhakhar** [comment]
Fixed by pull request: https://github.com/ql-io/ql.io/pull/516
