### ISSUE TITLE
ql.io V0.7.3 jsonpath selector issue

### ISSUE THREAD

**Issue by v3n3** [ql-io/ql.io#526]
i have the following object:

[[{"Code10":"35180932BS","ColorId":7,"RelatedItems":[]}],[{"Code10":"39278277KW","ColorId":7,"RelatedItems":[]}],[{"Code10":"34277431FH","ColorId":7,"RelatedItems":[]}],[{"Code10":"41309000FF","ColorId":6,"RelatedItems":[]},{"Code10":"41309000AM","ColorId":7,"RelatedItems":[]}],[{"Code10":"41297100UV","ColorId":7,"RelatedItems":[]}],[{"Code10":"37396018MK","ColorId":70,"RelatedItems":[]},{"Code10":"37396018UR","ColorId":7,"RelatedItems":[]}],[{"Code10":"41300487WA","ColorId":7,"RelatedItems":[]},{"Code10":"41300487TS","ColorId":7621,"RelatedItems":[]}],[{"Code10":"37378693SE","ColorId":7,"RelatedItems":[]},{"Code10":"37378693JU","ColorId":22,"RelatedItems":[]}],[{"Code10":"37390905NX","ColorId":7,"RelatedItems":[]}],[{"Code10":"36333357VE","ColorId":7,"RelatedItems":[]}]]

if i run the query $._._, it returns :

[["35180932BS",7],["39278277KW",7],["34277431FH",7],["41309000FF",6,"41309000AM",7],["41297100UV",7],["37396018MK",70,"37396018UR",7],["41300487WA",7,"41300487TS",7621],["37378693SE",7,"37378693JU",22],["37390905NX",7],["36333357VE",7]]

instead of :

[
   {
      "Code10":"35180932BS",
      "ColorId":7,
      "RelatedItems":[

```
  ]
```

   },
   {
      "Code10":"39278277KW",
      "ColorId":7,
      "RelatedItems":[

```
  ]
```

   },
   {
      "Code10":"34277431FH",
      "ColorId":7,
      "RelatedItems":[

```
  ]
```

   },
   {
      "Code10":"41309000FF",
      "ColorId":6,
      "RelatedItems":[

```
  ]
```

   },
   {
      "Code10":"41309000AM",
      "ColorId":7,
      "RelatedItems":[

```
  ]
```

   },
   {
      "Code10":"41297100UV",
      "ColorId":7,
      "RelatedItems":[

```
  ]
```

   },
   {
      "Code10":"37396018MK",
      "ColorId":70,
      "RelatedItems":[

```
  ]
```

   },
   {
      "Code10":"37396018UR",
      "ColorId":7,
      "RelatedItems":[

```
  ]
```

   },
   {
      "Code10":"41300487WA",
      "ColorId":7,
      "RelatedItems":[

```
  ]
```

   },
   {
      "Code10":"41300487TS",
      "ColorId":7621,
      "RelatedItems":[

```
  ]
```

   },
   {
      "Code10":"37378693SE",
      "ColorId":7,
      "RelatedItems":[

```
  ]
```

   },
   {
      "Code10":"37378693JU",
      "ColorId":22,
      "RelatedItems":[

```
  ]
```

   },
   {
      "Code10":"37390905NX",
      "ColorId":7,
      "RelatedItems":[

```
  ]
```

   },
   {
      "Code10":"36333357VE",
      "ColorId":7,
      "RelatedItems":[

```
  ]
```

   }
]

thank you in advance,

**Comment by shimonchayim** [comment]
I think you meant to use $.*
