### ISSUE TITLE
Or statement || 

### ISSUE THREAD

**Issue by hochang** [ql-io/ql.io#530]
e.g
ret1 = select ...... (some expensive operation)
ret2 = select ..... (some cheaper operation)
ret3 = ret1 || ret2
return ret3

ret1 and ret2 are executed parallelly, since ret2 returns faster, ret3 would catch ret2 and stops waiting for ret1.

**Comment by s3u** [comment]
Yes, but the compiler can't optimize this today without collapsing the script to

```
return select ...... (some expensive operation) || select ..... (some cheaper operation)
```

but generalizing this is a bit tricky in the presence of variable references and monkey patching.
