### ISSUE TITLE
Sqoot API Not Working

### ISSUE THREAD

**Issue by fayaza** [ql-io/ql.io#531]
Recently i am aware of ql io... and i am working on sqoot api which i want to run in ql io console.. but some how the the console body returns empty result [] and in trace it give the result output in xml which is correct......... when i install node js module ql.io-engine its happen same no result in body... How can i get the json output with my result set in console and as well as in node js app;

sample query :
"create table myoffers on select get from 'https://api.sqoot.com/v1/offers?affiliate_token=3fvbuh&location={loc }&order=score&page=1&per_page=5' resultset 'result.offers.offer' select \* from myoffers where loc = 'sanfrancisco';"

if i am missing anything in the query or is there anything which can make my work around... please let me know ASAP....

**Comment by fayaza** [comment]
https://api.sqoot.com/v1/offers?affiliate_token=3fvbuh&location=sanfrancisco&per_page=10&page=1&order=score&page_size=10

above is the sample GET REQUEST which can run on browser but not on ql.io console / ql io engine

**Comment by mtipnis** [comment]
Answered on discussion forum : https://groups.google.com/forum/?fromgroups#!topic/qlio/m223wXFar-E

**Comment by fayaza** [comment]
Yap... i got it.... thank you very much.. i was treated the same result set in YQL thats why did not bother to change it.. anyways its works.. thanks..
