### ISSUE TITLE
Execution plan and hints

### ISSUE THREAD

**Issue by prabhakhar** [ql-io/ql.io#537]
1. Command line utility to display the execution plan (like oracle/mysql)
2. Allow user to specify hints so that the generated plan is highly optimal.

Thanks to Sri for proposing this feature.

**Comment by s3u** [comment]
(1) is easily doable with a small script on top of ql.io-compiler like it is done in https://gist.github.com/2898080

**Comment by shimonchayim** [comment]
Displaying of execution plan now achieved through debug visualization and orchestration value is assumed to be higher because of auto-detection of paths (customer feedback). Closing this request.
