### ISSUE TITLE
Get EINVAL for valid utf-8 payload

### ISSUE THREAD

**Issue by shimonchayim** [ql-io/ql.io#548]
The issue seems to because we are doing Iconv conversion on chunks. Likely there is a byte alignment issues. Following code in verb.js seems to be the problem.

 this['parse response'] = function(args) { // Just append bufs to a string
        var encoding = 'UTF-8';
        if(args.headers['content-type']) {
            var contentType = headers.parse('content-type', args.headers['content-type'] || '');
            encoding = contentType.params.charset ? contentType.params.charset :
                contentType.subtype === 'csv' ? 'ASCII' : 'UTF-8';
        }
        var str = '';
        var iconv = new Iconv(encoding, 'UTF-8');
        _.each(args.body, function(buf) {
            buf = (iconv.convert(buf));
            str += buf.toString('UTF-8');
        });
        return {
            content: str
        };
    };

**Comment by shimonchayim** [comment]
Can you also port the changes to 0.6 Branch?

**Comment by idralyuk** [comment]
Done: https://github.com/ql-io/ql.io/commit/5641082254688eb9aae018a20689b0dbc87739b7
