### ISSUE TITLE
Does ql.io supports many-to-many relationship in join?

### ISSUE THREAD

**Issue by khurrumqureshi** [ql-io/ql.io#550]
Have a look at my script

create table winestyleattribs on select get from "http://api-botnik-com.herokuapp.com/v0.1/service/name/WineStyleAttribs.json"
resultset "values";

create table wines on select get from "http://api-botnik-com.herokuapp.com/v0.1/service/name/KlWines.json"
resultset "values";

select "a.row_values[_].color" as color,"a.row_values[_].varietal_area" as varietal_area, "w.row_values[*].varietal_area" as varietal
from winestyleattribs as a, wines as w
where w.varietal = a.varietal_area

I am trying to get data from above two services by joining on "varietal_area" both services has duplicate enteries for varietal_area which makes many-to-many relationship when i execute this it will makes multiple calls to the API which is an odd behavior.  Individually each service runs perfectly through ql.io but through join it does not works. Can anyone tell me the reason for that?

**Comment by khurrumqureshi** [comment]
columns is like a.row_values[*].varietal_area actually editor make it like the above

**Comment by hochang** [comment]
At this point, this feature is not available.
