### ISSUE TITLE
Select commands are not running sequentially.

### ISSUE THREAD

**Issue by khurrumqureshi** [ql-io/ql.io#553]
As per documentation http://ql.io/docs/variable-ref

resp = select \* from someDeepCollection;
ids = "{resp.$..ItemID}";
details = select \* from someDeetails where id in ("{ids}");

This script first gets the complete response of the collection, and then looks for ItemIDs. It then uses those IDs to find details. While the first statement involves a network round-trip, the second statement happens in memory.

What i understand from this is select commands run sequentially rather than parallel. but when i am doing this in my script

create table styles on select get from "http://api-botnik-com.herokuapp.com/v0.1/service/name/wine_styles.json"
resultset "values";
create table wines on select get from "http://api-botnik-com.herokuapp.com/v0.1/service/name/KlWines.json"
resultset "values";

t_style = select "row_values[_].age_potential" as agepotential, "row_values[_].adventurous" as adventurous,"row_values[_].wine_style" as wineStyle,"row_values[_].varietal_area" as varietal_area from styles;
t_wines = select \* from wines;
t_wineStyle=select "tw.row_values[_].varietal_area" as varietal_area,s.wineStyle as wineStyle from t_wines as tw, t_style as s where "tw.row_values[_].varietal_area"=s.varietal_area;

It is suppose to get result first for t_style than for t_wines and in the end for t_wineStyle but, interestingly it is not happening it get result first for t_style than for t_wines while in process it start fetching result for t_wineStyle don't wait to get t_wines finishes. Which cause to get incomplete result set means this query suppose to return 1500+ records but it returns only 33. Is it the  normal behavior of ql.io or i am doing something wrong.

**Comment by hochang** [comment]
This issue is merged with #552. Problem is detected, please allow us some time to handle this.
