### ISSUE TITLE
if-else script returns wrong result

### ISSUE THREAD

**Issue by mtipnis** [ql-io/ql.io#567]
if (x||y)
{
  q= 12345
  if (!j )
  { 
     g = 'sad'
  }
  else 
  {
     d= 'sleepy'
  }  
}
else 
{
   e = 'enjoy'
}
return q||g|| d||e;

Ans: "sad"

This doesn't look like correct behavior for the if-else statement

**Comment by hochang** [comment]
problem detected, skipVar trigger a skipped var's listener that should also be skipped.

**Comment by hochang** [comment]
fixed in #568
