### ISSUE TITLE
Upgrade to node >=0.6

### ISSUE THREAD

**Issue by s3u** [ql-io/ql.io#57]
Potential things to watch out
- Incompatibilities in modules?
- Cluster?
- Mon module may need significant tweaks

**Comment by s3u** [comment]
Also need https://github.com/polotek/libxmljs/pull/85

**Comment by prabhakhar** [comment]
modules compiler, uri-template and mutable uri tests passes without issues after node upgrade to 0.6.3

**Comment by s3u** [comment]
engine is clear

**Comment by s3u** [comment]
console is clear

**Comment by s3u** [comment]
Bumped into cluster!

**Comment by s3u** [comment]
Pushed the changes to branch https://github.com/s3u/ql.io/commits/node0.6

Cluster is work in progress.

**Comment by s3u** [comment]
Things to do:
- Start, stop and shutdown
- Counters 
- Initializing log dir

**Comment by s3u** [comment]
Except counters, the rest is done!

**Comment by s3u** [comment]
Replaced cluster. All tests pass now. See https://github.com/s3u/ql.io/tree/node0.6.

Next up: check start/stop/shutdown scripts

**Comment by s3u** [comment]
See the branch https://github.com/ql-io/ql.io/tree/0.4 for the ongoing work.

**Comment by s3u** [comment]
This is now done.
