### ISSUE TITLE
Type error: can not read property

### ISSUE THREAD

**Issue by s3u** [ql-io/ql.io#78]
Try

-- blah
--blah
--blah

in the console. You will get a type error and a few abnormalities:
- In Chrome/FF, the flight icon starts.
- In Safari, the response does not get rendered properly.

**Comment by shimonchayim** [comment]
Can we please put the merge id when we close the issue.

**Comment by shimonchayim** [comment]
00ba854

**Comment by s3u** [comment]
Also try trailing comments

http://ql.io/console?s=show%20tables%3B%0A--%20blah

**Comment by prabhakhar** [comment]
commit - 4d1ce967b6e46f61df087dc45bb1ae430edce9d4

**Comment by arekatla** [comment]
verified the fix, the issue has been addressed
