### ISSUE TITLE
Initialize global.opts.logger in engine

### ISSUE THREAD

**Issue by s3u** [ql-io/ql.io#92]
if not already initialized. Need something like

```
global.opts.logger = global.opts.logger || logger;
```

in lib/engine.js

**Comment by arekatla** [comment]
As global.opts.logger is not initialized, the actual error has not been surfaced when my ql has a patch script.
I see the TypeError: Cannot call method 'error' of undefined
   at Object.go (/home/rarekatla/stack/ql.io.myfork/modules/engine/lib/engine/brew.js:85:16)
   at Object.exec (/home/rarekatla/stack/ql.io.myfork/modules/engine/lib/engine/create.js:29:10)
   at _execOne (/home/rarekatla/stack/ql.io.myfork/modules/engine/lib/engine.js:340:20)

Upon debug, the below has been surfaced.

Error: Cannot find module '/private/tmp/ql.io/modules/engine/lib/engineresponse-patch.js'

debug: ERROR: {"stack":"Error: Cannot find module '/private/tmp/ql.io/modules/engine/lib/engineresponse-patch.js'\n    at Function._resolveFilename (module.js:317:11)\n    at Function._load (module.js:262:25)\n    at require (module.js:346:19)\n    at _process (/private/tmp/ql.io/modules/engine/lib/engine/brew.js:152:32)\n    at /private/tmp/ql.io/modules/engine/lib/engine/brew.js:73:21\n    at Array.forEach (native)\n    at Function.<anonymous> (/private/tmp/ql.io/modules/engine/node_modules/underscore/underscore.js:81:11)\n    at Object.go (/private/tmp/ql.io/modules/engine/lib/engine/brew.js:53:11)\n    at Object.exec (/private/tmp/ql.io/modules/engine/lib/engine/create.js:29:10)\n    at _execOne (/private/tmp/ql.io/modules/engine/lib/engine.js:342:20)","message":"Cannot find module '/private/tmp/ql.io/modules/engine/lib/engineresponse-patch.js'"}

Error with uri - http://localhost:3000/FindItemsResponsePatch.json - ECONNREFUSED, Connection refused

debug: ERROR: {"stack":"Error: ECONNREFUSED, Connection refused\n    at Socket._onConnect (net.js:601:18)\n    at IOWatcher.onWritable [as callback](net.js:186:12)","message":"ECONNREFUSED, Connection refused","errno":61,"code":"ECONNREFUSED","syscall":"connect","uri":{"value":"http://localhost:3000/FindItemsResponsePatch.json","length":49}}
