### ISSUE TITLE
Port ql.io to another programming language

### ISSUE THREAD

**Issue by nichtich** [ql-io/ql.io#93]
Right now ql.io is written in JavaScript with node.js. That's fine, but this way it does not look like a solution to the infrastructure and design problem of APIs described in [in this posting](http://www.subbu.org/blog/2011/11/apis-are-a-pain) but like an average piece of software. I expected a language-independent specification instead. As far as I understand ql.io, this specification is buried in ql.io as the DSL: http://ql.io/docs/lang-overview

**Comment by s3u** [comment]
The core of ql.io is the DSL and it can be used in two ways
1. as an HTTP gateway that takes script/route requests, does the necessary orchestration and responds with the results
2. directly from Nodejs based apps.

Implementing in multiple languages is a complex and expensive undertaking, and hence I would recommend using it as a gateway.

**Comment by s3u** [comment]
The language spec is at http://66.211.164.71/docs/reference/ql

**Comment by nichtich** [comment]
Thanks for the link and explanation. So ql.io is an implementation of "the DSL of ql.io" in JavaScript. I suggest to always refer to the DSL by a more unique name (QL Script?) than DSL or even the misnomer "ql.io script". The acronym QLS seems not to be used too much already, so I'll name it 'QLS' in the following. It should not be hard to write a QLS parser in other programming languages, if needed, but syntax is only one part - you also need to specify the semantics.

So QLS can be used to define "HTTP gateways that takes script/route requests, does the necessary orchestration and responds with the results". Sounds great. What I am hoping for - and the reason for this issue - is that with QLS you can define such gateways in a way that does not depend on a particular programming language (here: JavaScript). If you compare it with HTTP, REST, RPC, SOAP or similar technologies: these are architecture principles and standards, no matter what programming language the first web servers, browsers and other clients are written in. If ql.io compares to this, I would give it a try. If not, it is  just a random framework build on node.js, irrelevant to all web developers that happen to not use node.js.

If you know any Perl hackers in your community, maybe they can implement QLS and port ql.io as PSGI application - this seems to match very well. By the way [miyagawa](https://github.com/miyagawa) has similar problems with the distinction between Plack and PSGI as you with ql.io and its DSL.
